development:
  mysql:
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    password: 'password'
    database: 'database'
    
  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''

test:
  mysql:
    host: 'testhost'
    port: 3306
    user: 'root'
    password: 'password'
    database: 'database'
  
  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''  

prodution:
  mysql:
    host: 'produtionhost'
    port: 3306
    user: 'root'
    password: '123'
    database: 'prodution'
  
  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''  