development:
  mysql:
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    password: 'windows2010..'
    database: 'iotdata_development'

  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''

test:
  mysql:
    host: '106.15.202.75'
    port: 3306
    user: 'root'
    password: 'windows2010..'
    database: 'iotdata_development'
  
  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''  

prodution:
  mysql:
    host: 'produtionhost'
    port: 3306
    user: 'root'
    password: '123'
    database: 'prodution'
  
  redis:
    host: '127.0.0.1'
    port: 6379
    auth_pass: ''  